### ISSUE TITLE
Sync Failed!

### ISSUE THREAD

**Issue by Aashima-Gupta** [div1090/Face-Recognition-on-Android#3]
Hi, After i cloned the project, it seems to be showing errors in the external libraries. Pls Help.

Build command failed.

Error while executing process C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app -BC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\.externalNativeBuild\cmake\release\x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\build\intermediates\cmake\release\obj\x86_64 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_CXX_FLAGS= -DCMAKE_TOOLCHAIN_FILE=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}

-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

CMake Error at CMakeLists.txt:13 (find_package):

  Could not find a package configuration file provided by "OpenCV" with any

  of the following names:

    OpenCVConfig.cmake

    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set

  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"

  provides a separate development package or SDK, be sure it has been

  installed.

-- Configuring incomplete, errors occurred!

See also "C:/Users/guptaa82/Desktop/div1090 Face Recognition/Face-Recognition-on-Android/app/.externalNativeBuild/cmake/release/x86_64/CMakeFiles/CMakeOutput.log".

Build command failed.

Error while executing process C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app -BC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\.externalNativeBuild\cmake\debug\x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\build\intermediates\cmake\debug\obj\x86_64 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_CXX_FLAGS= -DCMAKE_TOOLCHAIN_FILE=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}

-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

CMake Error at CMakeLists.txt:13 (find_package):

  Could not find a package configuration file provided by "OpenCV" with any

  of the following names:

    OpenCVConfig.cmake

    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set

  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"

  provides a separate development package or SDK, be sure it has been

  installed.

-- Configuring incomplete, errors occurred!

See also "C:/Users/guptaa82/Desktop/div1090 Face Recognition/Face-Recognition-on-Android/app/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeOutput.log".

**Comment by div1090** [comment]
Hi @Aashima-Gupta, 
CMake is the one that's failing. You need to set up OpenCVAndroidSDK on your machine and set the `OpenCV_DIR` variable in `Face-Recognition-on-Android/app/CMakeLists.txt` to the corresponding path on your local machine. 

Instructions to download the sdk are here - https://docs.opencv.org/2.4/doc/tutorials/introduction/android_binary_package/O4A_SDK.html

Let me know if this fixes the issue? I'll see if I can wrap it better

**Comment by Aashima-Gupta** [comment]
I got this error..

Build command failed.
Error while executing process C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\.externalNativeBuild\cmake\debug\arm64-v8a --target native-lib}
[1/4] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/FaceTracker_jni.cpp.o
[2/4] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
[3/4] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/FaceRecognizer_jni.cpp.o
FAILED: C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android --gcc-toolchain=C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -isystem C:/Opencv-android-sdk/sdk/native/jni/include -isystem C:/Opencv-android-sdk/sdk/native/jni/include/opencv -isystem C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sources/android/support/include -isystem C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/FaceTracker_jni.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\FaceTracker_jni.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/FaceTracker_jni.cpp.o -c "C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\src\main\cpp\FaceTracker_jni.cpp"
C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\src\main\cpp\FaceTracker_jni.cpp:3:10: fatal error: 'opencv2/contrib/detection_based_tracker.hpp' file not found
#include <opencv2/contrib/detection_based_tracker.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android --gcc-toolchain=C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -isystem C:/Opencv-android-sdk/sdk/native/jni/include -isystem C:/Opencv-android-sdk/sdk/native/jni/include/opencv -isystem C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sources/android/support/include -isystem C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/FaceRecognizer_jni.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\FaceRecognizer_jni.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/FaceRecognizer_jni.cpp.o -c "C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\src\main\cpp\FaceRecognizer_jni.cpp"
C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\src\main\cpp\FaceRecognizer_jni.cpp:3:10: fatal error: 'opencv2/contrib/contrib.hpp' file not found
#include "opencv2/contrib/contrib.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by Aashima-Gupta** [comment]
Hey, Why haven't you included Android.mk and Application.mk files in external Libraries

**Comment by Aashima-Gupta** [comment]
Here in the contrib folder there is no path like

opencv>modules>contrib>include>opencv2>contrib>contrib.hpp

**Comment by skynetandroiddev** [comment]
I have bulid project successfully, then when i try to run the project i get the following issue.

Build command failed.
Error while executing process /Users/bhachu/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/bhachu/AndroidStudioProjects/Demo/Face-Recognition-on-Android-master/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target native-lib}
[1/3] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/FaceTracker_jni.cpp.o
[2/3] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/FaceRecognizer_jni.cpp.o
FAILED: /Users/bhachu/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/bhachu/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/bhachu/Library/Android/sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -isystem /Users/bhachu/OpenCV-android-sdk/sdk/native/jni/include -isystem /Users/bhachu/OpenCV-android-sdk/sdk/native/jni/include/opencv -isystem /Users/bhachu/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /Users/bhachu/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /Users/bhachu/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/FaceTracker_jni.cpp.o -MF CMakeFiles/native-lib.dir/src/main/cpp/FaceTracker_jni.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/FaceTracker_jni.cpp.o -c /Users/bhachu/AndroidStudioProjects/Demo/Face-Recognition-on-Android-master/app/src/main/cpp/FaceTracker_jni.cpp
/Users/bhachu/AndroidStudioProjects/Demo/Face-Recognition-on-Android-master/app/src/main/cpp/FaceTracker_jni.cpp:3:10: fatal error: 'opencv2/contrib/detection_based_tracker.hpp' file not found
#include <opencv2/contrib/detection_based_tracker.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/bhachu/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/bhachu/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/bhachu/Library/Android/sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -isystem /Users/bhachu/OpenCV-android-sdk/sdk/native/jni/include -isystem /Users/bhachu/OpenCV-android-sdk/sdk/native/jni/include/opencv -isystem /Users/bhachu/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /Users/bhachu/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /Users/bhachu/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/FaceRecognizer_jni.cpp.o -MF CMakeFiles/native-lib.dir/src/main/cpp/FaceRecognizer_jni.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/FaceRecognizer_jni.cpp.o -c /Users/bhachu/AndroidStudioProjects/Demo/Face-Recognition-on-Android-master/app/src/main/cpp/FaceRecognizer_jni.cpp
/Users/bhachu/AndroidStudioProjects/Demo/Face-Recognition-on-Android-master/app/src/main/cpp/FaceRecognizer_jni.cpp:3:10: fatal error: 'opencv2/contrib/contrib.hpp' file not found
#include "opencv2/contrib/contrib.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by div1090** [comment]
Hi guys, 

Thank you for reporting the issues. I'm working on making this compilable out of the box & creating a proper guide with the right versions of opencv sdks I'm using. The api changes a lot between different opencv versions. 

Also, will put up the apk in a bit. Thanks for being patient!

**Comment by skynetandroiddev** [comment]
Thanks. Please notify when you update.

**Comment by Aashima-Gupta** [comment]
Hi
Thanks.  Pls notify soon with the latest updates.

**Comment by div1090** [comment]
Hi @Aashima-Gupta @skynetandroiddev 

Thanks for being patient. Check the ReadMe now. There's a link to the exact versions that I have verified again to compile and build on a fresh machine. There's also a link the apk. 

Let me know if this fixes your build issues (the version of OpenCV SDK you have, where it complains about contrib files is definitely OpenCV 3.0+ which is not distributed with the contrib libraries). So I'm sticking with OpenCV 2.4 for now. Will work on moving to 3.0+ because that allows compatibility to all architectures.. but that will take some time.. may be in the next week.

**Comment by Aashima-Gupta** [comment]
Do we have to clone the project again?

**Comment by Aashima-Gupta** [comment]
Hi, I cloned the project again with newer OpenCV sdk version 2.4.13.3 and still the project is not syncing.

Build command failed.


Error while executing process C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app -BC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\.externalNativeBuild\cmake\release\x86 -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\build\intermediates\cmake\release\obj\x86 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_CXX_FLAGS= -DCMAKE_TOOLCHAIN_FILE=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}


-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe


-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works


-- Detecting C compiler ABI info


-- Detecting C compiler ABI info - done


-- Detecting C compile features


-- Detecting C compile features - done


-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe


-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works


-- Detecting CXX compiler ABI info


-- Detecting CXX compiler ABI info - done


-- Detecting CXX compile features


-- Detecting CXX compile features - done


CMake Error at CMakeLists.txt:12 (set):


    C:/Users/guptaa82/Desktop/div1090 Face Recognition/Face-Recognition-on-Android/app/CMakeLists.txt:12


  when parsing string


    C:\OpenCV-android-sdk\sdk\native\jni


  Invalid character escape '\O'.


-- Configuring incomplete, errors occurred!


See also "C:/Users/guptaa82/Desktop/div1090 Face Recognition/Face-Recognition-on-Android/app/.externalNativeBuild/cmake/release/x86/CMakeFiles/CMakeOutput.log".


Build command failed.


Error while executing process C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app -BC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\.externalNativeBuild\cmake\debug\x86 -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\build\intermediates\cmake\debug\obj\x86 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_CXX_FLAGS= -DCMAKE_TOOLCHAIN_FILE=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}


-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe


-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works


-- Detecting C compiler ABI info


-- Detecting C compiler ABI info - done


-- Detecting C compile features


-- Detecting C compile features - done


-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe


-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works


-- Detecting CXX compiler ABI info


-- Detecting CXX compiler ABI info - done


-- Detecting CXX compile features


-- Detecting CXX compile features - done


CMake Error at CMakeLists.txt:12 (set):


    C:/Users/guptaa82/Desktop/div1090 Face Recognition/Face-Recognition-on-Android/app/CMakeLists.txt:12


  when parsing string


    C:\OpenCV-android-sdk\sdk\native\jni


  Invalid character escape '\O'.


-- Configuring incomplete, errors occurred!


See also "C:/Users/guptaa82/Desktop/div1090 Face Recognition/Face-Recognition-on-Android/app/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeOutput.log".

**Comment by Aashima-Gupta** [comment]
ohk..the error is fixed!

**Comment by Aashima-Gupta** [comment]
I added missing files in jnilibs folder and then the error was:

Build command failed.


Error while executing process C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app -BC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\.externalNativeBuild\cmake\release\x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\build\intermediates\cmake\release\obj\x86_64 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_CXX_FLAGS= -DCMAKE_TOOLCHAIN_FILE=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}


-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe


-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works


-- Detecting C compiler ABI info


-- Detecting C compiler ABI info - done


-- Detecting C compile features


-- Detecting C compile features - done


-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe


-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works


-- Detecting CXX compiler ABI info


-- Detecting CXX compiler ABI info - done


-- Detecting CXX compile features


-- Detecting CXX compile features - done


 
Open File


    C:/OpenCV-android-sdk/sdk/native/jni/OpenCVModules_x86_64.cmake


Call Stack (most recent call first):


  CMakeLists.txt:13 (find_package)


-- OpenCV libraries: opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_photo;opencv_video;opencv_videostab;opencv_ts;opencv_ml;opencv_objdetect;opencv_ocl;opencv_superres;opencv_stitching;opencv_legacy;opencv_contrib


-- Configuring incomplete, errors occurred!


See also "C:/Users/guptaa82/Desktop/div1090 Face Recognition/Face-Recognition-on-Android/app/.externalNativeBuild/cmake/release/x86_64/CMakeFiles/CMakeOutput.log".


Build command failed.


Error while executing process C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app -BC:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\.externalNativeBuild\cmake\debug\x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\guptaa82\Desktop\div1090 Face Recognition\Face-Recognition-on-Android\app\build\intermediates\cmake\debug\obj\x86_64 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_CXX_FLAGS= -DCMAKE_TOOLCHAIN_FILE=C:\Users\guptaa82\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\guptaa82\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}


-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe


-- Check for working C compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works


-- Detecting C compiler ABI info


-- Detecting C compiler ABI info - done


-- Detecting C compile features


-- Detecting C compile features - done


-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe


-- Check for working CXX compiler: C:/Users/guptaa82/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works


-- Detecting CXX compiler ABI info


-- Detecting CXX compiler ABI info - done


-- Detecting CXX compile features


-- Detecting CXX compile features - done


 
Open File


    C:/OpenCV-android-sdk/sdk/native/jni/OpenCVModules_x86_64.cmake


Call Stack (most recent call first):


  CMakeLists.txt:13 (find_package)


-- OpenCV libraries: opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_photo;opencv_video;opencv_videostab;opencv_ts;opencv_ml;opencv_objdetect;opencv_ocl;opencv_superres;opencv_stitching;opencv_legacy;opencv_contrib


-- Configuring incomplete, errors occurred!


See also "C:/Users/guptaa82/Desktop/div1090 Face Recognition/Face-Recognition-on-Android/app/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeOutput.log".

**Comment by Aashima-Gupta** [comment]
The above error points to **OpenCVConfig.cmake** and i dont think any changes have to be made in this file/

**Comment by div1090** [comment]
I think the problem is it is not able to locate these files on your machine.. What OS are you using? Do you have the `.cmake` files in the path that it's looking at? 

If you have set the OpenCV_DIR variable in your environment, can you verify that it is not being re-written in the CMakeLists.txt file? 

Also in the previous errors it seems like it is complaining about the escape character. Try changing it to forward slash? (this can be machine/os specific sometimes)

**Comment by div1090** [comment]
@Aashima-Gupta  I just noticed the error logs are looking for x86_64 architecture... unfortunately it is not supported by opencv 2.4 (as mentioned in the readme). 

Could you test on a device that is compatible?
